### ISSUE TITLE
Issue with Zero Window Probing and Unreachable Primary Path

### ISSUE THREAD

**Issue by tuexen** [sctplab/rfc4960bis#12]
---
## Old text (Section 6.1):

If the sender continues to receive new packets from the receiver while doing zero window probing, the unacknowledged window probes should not increment the error counter for the association or any destination transport address. This is because the receiver MAY keep its window closed for an indefinite time. Refer to Section 6.2 on the receiver behavior when it advertises a zero window.

---
## New text (Section 6.1):

If the sender continues to receive SACKs from the receiver while doing zero window probing, the unacknowledged window probes should clear the error counter for the association or any destination transport address. This is because the receiver MAY keep its window closed for an indefinite time. Refer to Section 6.2 on the receiver behavior when it advertises a zero window.

Done.

**Comment by MaximProshin** [comment]
see proposed changes in https://github.com/sctplab/rfc4960bis/pull/35

**Comment by tuexen** [comment]
Fixed.
