### ISSUE TITLE
INIT ACK Path for INIT in COOKIE-WAIT State

### ISSUE THREAD

**Issue by tuexen** [sctplab/rfc4960bis#13]
---
## Old text (Section 5.2.1):

Upon receipt of an INIT in the COOKIE-WAIT state, an endpoint MUST respond with an INIT ACK using the same parameters it sent in its original INIT chunk (including its Initiate Tag, unchanged). When responding, the endpoint MUST send the INIT ACK back to the same address that the original INIT (sent by this endpoint) was sent.

---
## New text (Section 5.2.1):

Upon receipt of an INIT in the COOKIE-WAIT state, an endpoint MUST respond with an INIT ACK using the same parameters it sent in its original INIT chunk (including its Initiate Tag, unchanged). When responding, the following rules MUST be applied:

1) The INIT-ACK MUST only be sent to an address configured by the upper layer.

2) The INIT-ACK MUST only be sent to an address reported in the incoming INIT.

3) The INIT-ACK SHOULD be sent to the source address of the received INIT.

Done

**Comment by MaximProshin** [comment]
see proposed changes in https://github.com/sctplab/rfc4960bis/pull/38

**Comment by tuexen** [comment]
Committed.
