### ISSUE TITLE
Issues with Action B of Table 2

### ISSUE THREAD

**Issue by tuexen** [sctplab/rfc4960bis#15]
14.1    Description of the Problem:

Two issues have been found with the description of Action B of Table 2:
- The text assumes that when this initialization collision use case happens the endpoint may already be in the ESTABLISHED state while it is impossible. 
- The text does not cover the second row of Action B in the table when Peerís Tag is 0.  

14.2    Text Changes to the Document:

---
## Old text (Section 5.2.1):

B) In this case, both sides may be attempting to start an association at about the same time, but the peer endpoint started its INIT after responding to the local endpoint's INIT. Thus, it may have picked a new Verification Tag, not being aware of the previous tag it had sent this endpoint. The endpoint should stay in or enter the ESTABLISHED state, but it MUST update its peer's Verification Tag from the State Cookie, stop any init or cookie timers that may be running, and send a COOKIE ACK.

---
## New text (Section 5.2.1):

Bí) In this case, both sides may be attempting to start an association at about the same time, but the peer endpoint started its INIT after responding to the local endpoint's INIT. Thus, it may have picked a new Verification Tag, not being aware of the previous tag it had sent this endpoint. The endpoint should enter the ESTABLISHED state and MUST update its peer's Verification Tag from the State Cookie, stop any init or cookie timers that may be running, and send a COOKIE ACK.

Bíí) In this case, both sides may be attempting to start an association at about the same time and both sides received INIT in the COOKIE-WAIT state, but INIT from the peer is lost or received later than COOKIE-ECHO. Thus, the peerís Verification Tag is unknown at COOKIE ECHO receiving. The endpoint should enter the ESTABLISHED state and MUST update its peer's Verification Tag from the State Cookie, stop any init or cookie timers that may be running, and send a COOKIE ACK.

14.3    Solution Description:

The NEW text does not assume a situation when the endpoint is already in the ESTABLISHED state.

The Action B is split into two actions to address different scenarios. 

14.4    Note:

It is proposed that B is split into two different actions like Bí and Bíí above but in the RFC it should become B and C so that current C and D needs to be shifted.

Discuss via e-mail.

**Comment by MaximProshin** [comment]
in the proposed B'') is should be "... but **INIT ACK** from the peer is lost or received later than COOKIE-ECHO."

**Comment by MaximProshin** [comment]
see issue #14 where the use case is explained on the figure

**Comment by MaximProshin** [comment]
see proposed changes in https://github.com/sctplab/rfc4960bis/pull/33

**Comment by tuexen** [comment]
@MaximProshin If I remember it correctly, we discussed this and concluded that no change is required. Is that correct?

**Comment by MaximProshin** [comment]
yes, we agreed to close it without any changes in the draft.
