### ISSUE TITLE
Issue with Automatically CONFIRMED Addresses

### ISSUE THREAD

**Issue by tuexen** [sctplab/rfc4960bis#16]
Deal with the case that the addresses (plural!) reported by the upper layer does NOT match what the peer reports.
## Old text (Section 5.4):

1)  Any address passed to the sender of the INIT by its upper layer is automatically considered to be CONFIRMED.

---
## New text (Section 5.4):

1)  Any address passed to the sender of the INIT by its upper layer in the ASSOCIATE primitive is automatically considered to be CONFIRMED.

But we don't take the text.

**Comment by MaximProshin** [comment]
see proposed changes in https://github.com/sctplab/rfc4960bis/pull/37

**Comment by tuexen** [comment]
Fixed.
