### ISSUE TITLE
Outstanding Data, Flightsize and Data In Flight Terms 

### ISSUE THREAD

**Issue by tuexen** [sctplab/rfc4960bis#17]
---
## Old text (Section 1.3):

o  Congestion window (CWND): An SCTP variable that limits the data, in number of bytes, a sender can send to a particular destination transport address before receiving an acknowledgement.

o  Outstanding TSN (at an SCTP endpoint): A TSN (and the associated DATA chunk) that has been sent by the endpoint but for which it has not yet received an acknowledgement.

---
## New text (Section 1.3):

o  Outstanding TSN (at an SCTP endpoint): A TSN (and the associated DATA chunk) that has been sent by the endpoint but for which it has not yet received an acknowledgement.

o  Outstanding data (or Data in flight): DATA chunks associated with outstanding TSNs. A retransmitted DATA chunk is counted once in outstanding data. A DATA chunk which is classified is lost but which has not been retransmitted yet is not in outstanding data.

o  Flightsize: The amount of bytes of outstanding data to a particular destination transport address at any given time. 

o  Congestion window (CWND): An SCTP variable that limits outstanding data, in number of bytes, a sender can send to a particular destination transport address before receiving an acknowledgement.

**Comment by MaximProshin** [comment]
See proposed changes in https://github.com/sctplab/rfc4960bis/pull/43

**Comment by tuexen** [comment]
Fix in https://github.com/sctplab/rfc4960bis/commit/a519d2897e4168f3b3e6defcca74fdc407666a8f.
