### ISSUE TITLE
ssthresh Refresh after Idle Period 

### ISSUE THREAD

**Issue by tuexen** [sctplab/rfc4960bis#18]
## Old text (Section 7.2.1):

   o  The initial cwnd before DATA transmission or after a sufficiently
      long idle period MUST be set to min(4_MTU, max (2_MTU, 4380
      bytes)).

---
## New text (Section 7.2.1):

   o  The initial cwnd before DATA transmission  MUST be set to min(4_MTU, max (2_MTU, 4380
      bytes)).
## Old text (Section 7.2.1):

o  When the endpoint does not transmit data on a given transport address, the cwnd of the transport address should be adjusted to max(cwnd/2, 4*MTU) per RTO.

---
## New text (Section 7.2.1):

o  When the endpoint does not transmit data on a given transport address, the cwnd of the transport address should be adjusted to max(cwnd/2, 4*MTU) per RTO . At first reduction, store the cwnd in ssthresh.

**Comment by MaximProshin** [comment]
Proposed changes are in https://github.com/sctplab/rfc4960bis/pull/53.

**Comment by tuexen** [comment]
Merged.
