### ISSUE TITLE
Investigate supported address types parameter

### ISSUE THREAD

**Issue by tuexen** [sctplab/rfc4960bis#23]

**Comment by tuexen** [comment]
Take relationship to https://github.com/sctplab/rfc4960bis/issues/22 into account. If the hostname parameter is gone, we don't need this anymore.

**Comment by MaximProshin** [comment]
"Host Name Address" will be kept but marked as Deprecated.
"Supported Address Types" will be kept but "Host Name Address" will not be allowed there.
Agreed.

**Comment by MaximProshin** [comment]
The following inconsistent text was discussed and agreed to be improved (the text in bold should be rephrased):
5.1.2.  Handle Address Parameters
…
   Note: The INIT ACK MUST be sent to the source address of the INIT.
 
   The sender of INIT may include a 'Supported Address Types' parameter
   in the INIT to indicate what types of address are acceptable.  **When
   this parameter is present, the receiver of INIT (initiate) MUST
   either use one of the address types indicated in the Supported
   Address Types parameter when responding to the INIT, or abort the
   association with an "Unresolvable Address" error cause if it is
   unwilling or incapable of using any of the address types indicated by
   its peer.**
…
   IMPLEMENTATION NOTE: If an SCTP endpoint lists in the 'Supported
   Address Types' parameter either IPv4 or IPv6, but uses the other
   family for sending the packet containing the INIT chunk, or if it
   also lists addresses of the other family in the INIT chunk, then the
   address family that is not listed in the 'Supported Address Types'
   parameter SHOULD also be considered as supported by the receiver of
   the INIT chunk.  The receiver of the INIT chunk SHOULD NOT respond
   with any kind of error indication.
