### ISSUE TITLE
Inconsistency in Sections 8.2 and 8.3

### ISSUE THREAD

**Issue by MaximProshin** [sctplab/rfc4960bis#25]
RFC4960, Section 8.2, says that when a destination address becomes inactive due to an unacknowledged DATA or HEARTBEAT, SCTP **SHOULD** send a notification to the upper layer while Section 8.3 says that when a destination address becomes inactive due to an unacknowledged HEARTBEAT, SCTP **may** send a notification to the upper layer. This makes the text inconsistent. 

The proposal is to use SHOULD also in Section 8.3.

**Comment by MaximProshin** [comment]
The same should be checked and aligned for reporting of the Active destination state and perhaps the association state.

**Comment by MaximProshin** [comment]
see proposed changes in https://github.com/sctplab/rfc4960bis/pull/36

**Comment by tuexen** [comment]
Fix in https://github.com/sctplab/rfc4960bis/commit/9cc43d926b39ca66561b2b106e1d3d3c853840d9.
