### ISSUE TITLE
HB ACK and the association error counter

### ISSUE THREAD

**Issue by MaximProshin** [sctplab/rfc4960bis#26]
RFC4960 in Section 8.3 prescribes to clear the association error counter when HB ACK is received and 'must' is used for it. Following this rule blindly may result in problems in some specific use cases like when a router discards DATA/SACK but not HB/HB ACK. It is proposed to change the text so that it uses  SHOULD and then explains the reasons of MAY why not to clear the association error counter.

RFC4960 already uses SHOULD/should for clearing the destination error counter when HB ACK is received. It may also be beneficial to explain the reasons of MAY why not to clear the destination error counter.

**Comment by tuexen** [comment]
Fixed.
