### ISSUE TITLE
cwnd increase by more than MTU per RTT

### ISSUE THREAD

**Issue by MaximProshin** [sctplab/rfc4960bis#29]
The RFC does not clearly states that SCTP must not increase cwnd by more than one MTU per RTT. The text in Section 7.2.2 should be updated.
It should be decided what to do with partial_bytes_acked when it becomes equal or higher than cwnd but cwnd is not increased (either due to the condition above or due to flightsize which is less than cwnd).

**Comment by MaximProshin** [comment]
Currently I think that pba should be decreased by cwnd every time it becomes equal or greater than cwnd regardless of whether cwnd is adjusted then or not. Otherwise there is a risk that cwnd adjustment is triggered by old acks in pba.

**Comment by stewrtrs** [comment]
Actually thats not true.

An old ack is discarded upon entry.. don’t remember the passage but anything old is supposed
to be discarded.

R
On Oct 1, 2015, at 10:35 AM, Maxim notifications@github.com wrote:

> Currently I think that pba should be decreased by cwnd every time it becomes equal or greater than cwnd regardless of whether cwnd is adjusted then or not. Otherwise there is a risk that cwnd adjustment is triggered by old acks in pba.
> 
> —
> Reply to this email directly or view it on GitHub.

---

Randall Stewart
rrs@netflix.com
803-317-4952

**Comment by MaximProshin** [comment]
o  Whenever cwnd is greater than ssthresh, upon each SACK arrival
      that advances the Cumulative TSN Ack Point, increase
      partial_bytes_acked by the total number of bytes of all new chunks
      acknowledged in that SACK including chunks acknowledged by the new
      Cumulative TSN Ack and by Gap Ack Blocks.

   o  When partial_bytes_acked is equal to or greater than cwnd and
      before the arrival of the SACK the sender had cwnd or more bytes
      of data outstanding (i.e., before arrival of the SACK, flightsize
      was greater than or equal to cwnd), increase cwnd by MTU, and
      reset partial_bytes_acked to (partial_bytes_acked - cwnd).

If pba is increased according to the first rule for a long time but the condition in the second rule is not fulfilled then pba will be large and it will include bytes of TSNs acknowledged much time ago.  I've called them "old"

**Comment by tuexen** [comment]
Randy, I think you refer to SACKs for which the cum_tsn is less than the Cumulative TSN Ack Point.
The dropping of such SACK is required in https://tools.ietf.org/html/rfc4960#section-6.2.1:

```
   D) Any time a SACK arrives, the endpoint performs the following:

        i) If Cumulative TSN Ack is less than the Cumulative TSN Ack
           Point, then drop the SACK.  Since Cumulative TSN Ack is
           monotonically increasing, a SACK whose Cumulative TSN Ack is
           less than the Cumulative TSN Ack Point indicates an out-of-
           order SACK.
```

However, this is not, what Maxim is referring to.

**Comment by tuexen** [comment]
Three possible solutions:
- increase  partial_bytes_acked only if you have more than cwnd outstanding bytes.
- set partial_bytes_acked to 0 when you increase cwnd.
- if partial_bytes_acked >= cwnd, before SACK the sender has less than cwnd outstanding, reset partial_bytes_acked to cwnd
  Third solution chosen..

**Comment by karenegede** [comment]
- Our implementation followed the first option until ~2012, now it
  follows the second option.

I prefer option 2 from the perspective that it is a little more aggressive
in the ramps up as well as that the count of the bytes in partial_bytes_ack
during CWND underutilization may be used to give some indication of what
the validated CWND is. But I also recognize that the latter anyway is for
future use and might require maintain of additional state also.

I would even opt for that one could describe both as valid implementation
options.

BR, Karen

_From:_ Michael Tüxen [mailto:notifications@github.com]
_Sent:_ 5. april 2016 20:51
_To:_ sctplab/rfc4960bis rfc4960bis@noreply.github.com
_Subject:_ Re: [sctplab/rfc4960bis] cwnd increase by more than MTU per RTT
(#29)

Two possible solutions:
- increase partial_bytes_acked only if you have more than cwnd
  outstanding bytes.
- set partial_bytes_acked to 0 when you increase cwnd.

**Comment by MaximProshin** [comment]
See proposed changes in https://github.com/sctplab/rfc4960bis/pull/52

**Comment by tuexen** [comment]
Merged.
