### ISSUE TITLE
Delivery number parameter not explained in receive call

### ISSUE THREAD

**Issue by mwelzl** [sctplab/rfc4960bis#34]
Section 10.1, item G) - there is a parameter called "delivery number", but it's not explained in the list below (as the only one, which makes it easy to miss). This parameter is useful to detect reordering.

**Comment by MaximProshin** [comment]
Here is my simple proposal how to fix it:

Old text (Section 10.1):
   o  partial flag - if this returned flag is set to 1, then this
      Receive contains a partial delivery of the whole message.  When
      this flag is set, the stream id and Stream Sequence Number MUST
      accompany this receive.  When this flag is set to 0, it indicates
      that no more deliveries will be received for this Stream Sequence
      Number.

   o  payload protocol-id - a 32-bit unsigned integer that is received
      from the peer indicating the type of payload protocol of the
      received data.  This value is passed as opaque data by SCTP.

---

New text (Section 10.1):
   o  partial flag - if this returned flag is set to 1, then this
      Receive contains a partial delivery of the whole message.  When
      this flag is set, the stream id and Stream Sequence Number MUST
      accompany this receive.  When this flag is set to 0, it indicates
      that no more deliveries will be received for this Stream Sequence
      Number.

   o  **delivery number – the sequence number of a message
      assigned by the partial delivery mechanism.**

   o  payload protocol-id - a 32-bit unsigned integer that is received
      from the peer indicating the type of payload protocol of the
      received data.  This value is passed as opaque data by SCTP.

**Comment by MaximProshin** [comment]
Probably we also need to improve the description of the "partial flag" attribute because today it refers to stream id and SSN but not to "delivery number".

**Comment by stewrtrs** [comment]
MUST is not something for section 10

please read the intro to that section it is NOT  part of the standardized
section of the text it is an example API that an implementation does not
have to implement.

And directives in section 10 can NOT have the capital MUST, SHOULD... Etc

R

Sent from my iPhone

On Feb 29, 2016, at 8:01 AM, Maxim notifications@github.com wrote:

Here is my simple proposal how to fix it:

Old text (Section 10.1):
o partial flag - if this returned flag is set to 1, then this
Receive contains a partial delivery of the whole message. When
this flag is set, the stream id and Stream Sequence Number MUST
accompany this receive. When this flag is set to 0, it indicates
that no more deliveries will be received for this Stream Sequence
Number.

o payload protocol-id - a 32-bit unsigned integer that is received
from the peer indicating the type of payload protocol of the

## received data. This value is passed as opaque data by SCTP.

New text (Section 10.1):
o partial flag - if this returned flag is set to 1, then this
Receive contains a partial delivery of the whole message. When
this flag is set, the stream id and Stream Sequence Number MUST
accompany this receive. When this flag is set to 0, it indicates
that no more deliveries will be received for this Stream Sequence
Number.

*\* o delivery number – the sequence number of a message
delivered by the partial delivery mechanism.**

o payload protocol-id - a 32-bit unsigned integer that is received
from the peer indicating the type of payload protocol of the
received data. This value is passed as opaque data by SCTP.

**Comment by MaximProshin** [comment]
Randall, I totally agree with you! If you read carefully then you'll see that what I propose is the description in bold. "MUST" is the existing text but I agree that capital words cannot be used in Section 10. 
If we agree to update the "partial flag" attribute too, I'll be happy to remove MUST there...

**Comment by MaximProshin** [comment]
Btw, RECEIVE_UNSENT and RECEIVE_UNACKED do not have "delivery number" but it seems that they should also include it because partial delivery is possible in these cases too.

**Comment by MaximProshin** [comment]
A new issue has been created to remove MUST from Section 10: https://github.com/sctplab/rfc4960bis/issues/40

**Comment by tuexen** [comment]
OK. Coming back to the original issue: I don't understand how this stuff can/should work. How do you know that you got the final fragment of a message?
So why not change it to make it more aligned with the socket API:
1. Get rid of `delivery number`.
2. Say that `partial flag` means that this is not the final fragment.
3. Require the delivery of `stream id` and `stream sequence number` for all fragments of a user message when partial delivery is used.
4. Require that all fragments are delivered in order.

**Comment by MaximProshin** [comment]
Indeed there is no "delivery number" in Socket API but I think we need to understand what was the reason/intention of having this parameter in RFC4960. My understanding was that the goal of this parameter was to secure that SCTP user is always aware that it receives all fragments and it is able to disassemble the message with the right order of fragments regardless of the interface between the user and SCTP. I mean that if SCTP sends fragments in order, it does not mean that they will be received in order and can't be re-ordered somewhere in IPC.

Anyway, the section is informational so basically I don't have objections to simply remove this parameter.

**Comment by tuexen** [comment]
... and I was trying to understand the intention and failed... You can deliver the fragments in any order and use the `delivery number` to allow the upper layer to do the reassembly. That is what I deduce from the name. But how does the application know, that it has received the final fragment? Can you explain that by using the `stream id`, `stream sequence number`, `partial flag` and the `delivery number`. And while you are at that, can you also explain how this works for unordered messages, where the `stream sequence number` doesn't make any sense?

**Comment by MaximProshin** [comment]
Yes, there is no way to detect the final fragment and the delivery number parameter is insufficient so let's remove it.
