### ISSUE TITLE
Remove keywords (MUST, SHOULD...) from Section 10

### ISSUE THREAD

**Issue by MaximProshin** [sctplab/rfc4960bis#40]
Section 10 is informative and should not include keywords such as MUST. There are a few places where MUST is used today and it is proposed to remove it.

**Comment by MaximProshin** [comment]
See Randall's comment: https://github.com/sctplab/rfc4960bis/issues/34#issuecomment-190212397

**Comment by MaximProshin** [comment]
See the proposed changes and a comment in https://github.com/sctplab/rfc4960bis/pull/41

**Comment by tuexen** [comment]
Fixed.
