### ISSUE TITLE
Only one packet after T3

### ISSUE THREAD

**Issue by tuexen** [sctplab/rfc4960bis#5]
---
## Old text (Section 7.2.1):

o  The initial cwnd after a retransmission timeout MUST be no more than 1*MTU.

---
## New text (Section 7.2.1):

o  The initial cwnd after a retransmission timeout MUST be no more than 1*MTU and only one packet is allowed to be sent in flight until successful acknowledgement.

**Comment by MaximProshin** [comment]
Proposed changes are in https://github.com/sctplab/rfc4960bis/pull/39

**Comment by MaximProshin** [comment]
Fixed.
