### ISSUE TITLE
Include RFCs that update RFC4960

### ISSUE THREAD

**Issue by MaximProshin** [sctplab/rfc4960bis#50]
There are a few SCTP RFCs such as RFC6096 that update RFC4960 and could be incorporated into RFCbis.

**Comment by tuexen** [comment]
The RFCs updating [RFC 4960](https://tools.ietf.org/html/rfc4960) are:

- [RFC 6096](https://tools.ietf.org/html/rfc6096): Chunk Flags Registry
- [RFC 6335](https://tools.ietf.org/html/rfc6335): IANA Procedures for Service Name / Port Numbers
- [RFC 7053](https://tools.ietf.org/html/rfc7053): SACK-IMMEDIATELY Extension

I think the required changes are not very large and it makes sense to integrate them. We can bring this up at the TSVWG meeting in Prague.

**Comment by MaximProshin** [comment]
agreed, will be proposed in TSVWG

**Comment by tuexen** [comment]
Fixed by three commits.
