### ISSUE TITLE
Zero Window Probing when the peer's rwnd > 0

### ISSUE THREAD

**Issue by MaximProshin** [sctplab/rfc4960bis#56]
The RFC says:

>    A) At any given time, the data sender MUST NOT transmit new data to
>       any destination transport address **if its peer's rwnd indicates
>       that the peer has no buffer space (i.e., rwnd is 0**; see Section
>       6.2.1).  However, regardless of the value of rwnd (including if it
>       is 0), the data sender can always have one DATA chunk in flight to
>       the receiver if allowed by cwnd (see rule B, below).  This rule
>       allows the sender to probe for a change in rwnd that the sender
>       missed due to the SACK's having been lost in transit from the data
>       receiver to the data sender.
>       **When the receiver's advertised window is zero**, this probe is
>       called a zero window probe.  Note that a zero window probe SHOULD
>       only be sent when all outstanding DATA chunks have been
>       cumulatively acknowledged and no DATA chunks are in flight.  Zero
>       window probing MUST be supported.

I believe the intention of the RFC is to start zero window probing when the size of the next DATA chunk to be sent is more than available space in the peer's buffer, i.e. rwnd might be more than 0. 

Should it be clarified?

**Comment by tuexen** [comment]
Not sure what needs to be clarified. Can you make clear what behaviour you want to be allowed and is forbidden by the text or vice versa?

**Comment by MaximProshin** [comment]
The problem is that the highlighted text above may cause misunderstanding and someone (e.g. the operator) may think that SCTP behavior is against the RFC when he/she sees SACK with a_rwnd > 0 in traces but nevertheless SCTP stops new data sending and goes to zero window probing.

My idea was to clarify that, even though a_rwnd > 0, SCTP may start zero window probing if its next DATA chunk is more than available space in the peer's buffer. 

Possibly we could just replace "rwnd is 0" above by "rwnd is 0 or the size of the next DATA chunk to be sent is more than available space in the peer's buffer" and "When the receiver's advertised window is zero" by "When the peer has no buffer space". We could think about better formulation.
