### ISSUE TITLE
INIT-ACK vs INIT ACK, COOKIE-ACK vs COOKIE ACK

### ISSUE THREAD

**Issue by MaximProshin** [sctplab/rfc4960bis#58]
There are a few places where INIT-ACK is used instead of INIT ACK and COOKIE-ACK instead of COOKIE ACK. This makes the search operation more difficult. It could be aligned.

**Comment by MaximProshin** [comment]
It could be added into the existing section of the draft: 3.9.  Miscellaneous Typos

**Comment by tuexen** [comment]
I agree.

**Comment by MaximProshin** [comment]
Changes are made in https://github.com/sctplab/rfc4960bis/pull/59

**Comment by tuexen** [comment]
Merged.
