### ISSUE TITLE
Replace the ref to RFC1981 by a new RFC

### ISSUE THREAD

**Issue by MaximProshin** [sctplab/rfc4960bis#61]
draft-ietf-6man-rfc1981bis replaces RFC1981. Just to not forget to replace it.
Any other obsoleted RFCs referenced in RFC4960?

**Comment by tuexen** [comment]
The easiest way to deal with this is when actually working on rfc4960 bis. Referring to updated documents is part of the nits check, I think.

**Comment by MaximProshin** [comment]
I agree. My intention was to mention it to not forget about it and also make sure that it does not impact RFC4960. As far as I can see it does not impact and we will need to replace the ID only.
