### ISSUE TITLE
TSN used before defined

### ISSUE THREAD

**Issue by jonesmz** [sctplab/rfc4960bis#65]
The first use of the acronym TSN is on page 7.

> Cumulative TSN Ack Point: The TSN of the last DATA chunk
> acknowledged via the Cumulative TSN Ack field of a SACK.

TSN isn't defined until page 8.

> SCTP association: A protocol relationship between SCTP endpoints,
> composed of the two SCTP endpoints and protocol state information
> including Verification Tags and the currently active set of
> Transmission Sequence Numbers (TSNs), etc.  An association can be
> uniquely identified by the transport addresses used by the
> endpoints in the association.  Two SCTP endpoints MUST NOT have
> more than one SCTP association between them at any given time.

**Comment by tuexen** [comment]
The document has finished WG last call and is now in IETF LC. You can bring up that point at the IETF mailing list, but I consider it a minor thing...

**Comment by MaximProshin** [comment]
This is a minor editorial thing that we can easily do in RFC4960bis so I propose to just mark it "Do in RFC4960bis".

**Comment by tuexen** [comment]
@MaximProshin That is a good idea. I've done it.
