### ISSUE TITLE
Removal of port number registration request

### ISSUE THREAD

**Issue by tuexen** [sctplab/rfc4960bis#68]
Shouldn't the following text be removed?
```
This document registers the following ports.  (These registrations
should be considered models to follow for future allocation
requests.)

      discard    9/sctp  Discard  # IETF TSVWG
                                  # Randall Stewart <rrs@cisco.com>
                                  # [RFC4960]

         The discard service, which accepts SCTP connections on port
         9, discards all incoming application data and sends no data
         in response.  Thus, SCTP's discard port is analogous to
         TCP's discard port, and might be used to check the health
         of an SCTP stack.

      ftp-data  20/sctp  FTP      # IETF TSVWG
                                  # Randall Stewart <rrs@cisco.com>
                                  # [RFC4960]

      ftp       21/sctp  FTP      # IETF TSVWG
                                  # Randall Stewart <rrs@cisco.com>
                                  # [RFC4960]

         File Transfer Protocol (FTP) data (20) and control ports
         (21).

      ssh       22/sctp  SSH      # IETF TSVWG
                                  # Randall Stewart <rrs@cisco.com>
                                  # [RFC4960]

         The Secure Shell (SSH) remote login service, which allows
         secure shell logins to a host.

      http      80/sctp  HTTP     # IETF TSVWG
                                  # Randall Stewart <rrs@cisco.com>
                                  # [RFC4960]

         World Wide Web HTTP over SCTP.

      bgp      179/sctp  BGP      # IETF TSVWG
                                  # Randall Stewart <rrs@cisco.com>
                                  # [RFC4960]

         Border Gateway Protocol over SCTP.

      https    443/sctp  HTTPS    # IETF TSVWG
                                  # Randall Stewart <rrs@cisco.com>
                                  # [RFC4960]

         World Wide Web HTTP over TLS/SSL over SCTP.
```

**Comment by MaximProshin** [comment]
I guess Randall should comment it. I personally don't see any reason to keep this text but I'm might be mistaken.

**Comment by stewrtrs** [comment]
why?

R

> On Jul 1, 2019, at 3:58 AM, Maksim Proshin <notifications@github.com> wrote:
> 
> I guess Randall should comment it. I personally don't see any reason to keep this text but I'm might be mistaken.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

------
Randall Stewart
rrs@netflix.com

**Comment by tuexen** [comment]
Since it was in RFC 4960 the text to require IANA to make the allocations. Since these allocations have been made, we don't need to request them again in RFC 4960bis.

**Comment by stewrtrs** [comment]
ahh

But thats not true, it may be a request in the RFC, IANA decided *not* to do that for
SCTP. So there is no “every port for TCP is mapped to SCTP”.

R

> On Jul 1, 2019, at 6:50 AM, Michael Tüxen <notifications@github.com> wrote:
> 
> Since it was in RFC 4960 the text to require IANA to make the allocations. Since these allocations have been made, we don't need to request them again in RFC 4960bis.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

------
Randall Stewart
rrs@netflix.com

**Comment by tuexen** [comment]
I don't read [IANA considerations](https://tools.ietf.org/html/rfc4960#section-14.5) as a request to do all TCP assignment also for SCTP and this would does not follow the policy used by IANA right now.

My reading of [RFC 4960](https://tools.ietf.org/html/rfc4960#section-14.5) is that assignments for

- discard
- ftp-data
- ftp
- ssh
- http
- bgp
- https

where requested and according to [IANA](https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml) these assignments were made. The references for all of these assignments are [RFC 4960](https://tools.ietf.org/html/rfc4960).

**Comment by tuexen** [comment]
Talked to an IESG member which preferred to keep it...
